ALTER TABLE support_pages ADD COLUMN operator_name TEXT;
ALTER TABLE support_pages ADD COLUMN team_members TEXT NOT NULL DEFAULT '[]';

UPDATE support_pages
SET operator_name = 'Yogesh Kumar Kashyap',
    team_members = '[{"name":"Yogesh Kumar Kashyap","qualification":"Co Founder & Developer","image":"/trace-logo-square.png","summary":"Yogesh operates TracePG with a focus on building a dependable, student-first preparation workspace that makes practice, review, and progress easier to follow."},{"name":"Madhav Chandrakar","qualification":"MBBS, 3rd Yr Student · Founder","image":"/trace-logo-square.png","summary":"Madhav originated the core idea behind TracePG and helps shape the learning experience through thoughtful resource collection and a student’s perspective on postgraduate medical preparation."}]'
WHERE slug = 'about';

INSERT OR IGNORE INTO legal_pages (slug, label, title, intro, sections, updated_at)
VALUES ('shipping', 'Shipping Policy', 'Digital access, delivered without delay.', 'TracePG is a digital study platform. No physical products are shipped; your access is delivered electronically to your account.', '[["Digital delivery","After you sign in or complete an eligible purchase, TracePG access is provided electronically through your account at tracepg.com. There is no physical package or delivery address required."],["When access becomes available","Access is normally available immediately after account activation or successful payment confirmation. If access does not appear, refresh your session and contact support with your account email and transaction details."],["No physical shipping charges","Because TracePG provides digital study tools, there are no shipping fees, courier charges, or physical delivery timelines for the service."],["Access support","If a payment is successful but the service is not available to you, contact support@tracepg.com. We will verify the account and payment status and help restore access."],["Policy updates","We may update this policy when our delivery process or service changes. The version published on this page is the current version."]]', 0);
